name = P5chr

[ReadmeFromPod]
; disable = true
filename = doc/P5chr.rakudoc

[PruneFiles]
; match = ^ 'xt/'

[Badges]
provider = github-actions/linux.yml
provider = github-actions/macos.yml
provider = github-actions/windows.yml

[UploadToZef]
